FROM node:latest
WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB
ENV SECRET_KEY=$SECRET_KEY
ENV POSTGRES_HOST_AUTH_METHOD=$POSTGRES_HOST_AUTH_METHOD

RUN npm run build:prod

CMD npm run server
