export enum AppRoutes {
  basePath = 'https://redgreen.ya-praktikum.tech:3000',
  error500 = '/500',
  forum = '/forum',
  forumNew = '/forum/new',
  forumTopic = '/forum/topic',
  game = '/game',
  index = '/',
  leaderBoards = '/leaderboards',
  oauthRedirectUri = 'https://redgreen.ya-praktikum.tech:3000',
  profile = '/profile',
  profileEdit = '/profile/edit',
  profilePassword = '/profile/password',
  signIn = '/signin',
  signOut = '/signout',
  signUp = '/signup',
}
